const express = require("express");
const router = express.Router();

const galaktokomikaEidhPsugeiouController = require("../controller/apiControllers/galaktokomikaEidhPsugeiouController");
const fetchSingleProductController = require("../controller/apiControllers/fetchSingleProductController");

router.get("/", galaktokomikaEidhPsugeiouController.galaktokomikaEidhPsugeiou);
router.get("/gala", galaktokomikaEidhPsugeiouController.gala);
router.get("/gala/fresko-gala", galaktokomikaEidhPsugeiouController.freskoGala);
router.get("/gala/upshlhs-pasteriwshs", galaktokomikaEidhPsugeiouController.upshlhsPasteriwshs);
router.get("/gala/sokolatouxo", galaktokomikaEidhPsugeiouController.sokolatouxo);
router.get("/gala/futiko", galaktokomikaEidhPsugeiouController.futiko);
router.get("/gala/evapore", galaktokomikaEidhPsugeiouController.evapore);
router.get("/giaourti", galaktokomikaEidhPsugeiouController.giaourti);
router.get("/giaourti/ageladino", galaktokomikaEidhPsugeiouController.ageladino);
router.get("/giaourti/katsikisio", galaktokomikaEidhPsugeiouController.katsikisio);
router.get("/giaourti/proveio", galaktokomikaEidhPsugeiouController.proveio);
router.get("/giaourti/straggisto", galaktokomikaEidhPsugeiouController.straggisto);
router.get("/giaourti/epidorpio", galaktokomikaEidhPsugeiouController.epidorpio);
router.get("/giaourti/paidiko", galaktokomikaEidhPsugeiouController.paidiko);
router.get("/giaourti/rofhma", galaktokomikaEidhPsugeiouController.rofhma);
router.get("/freskes-zymes-fylla", galaktokomikaEidhPsugeiouController.freskesZymesFylla);
router.get("/freskes-zymes-fylla/gia-krouasan", galaktokomikaEidhPsugeiouController.giaKrouasan);
router.get("/freskes-zymes-fylla/gia-pitsa", galaktokomikaEidhPsugeiouController.giaPitsa);
router.get("/freskes-zymes-fylla/gia-sfoliata", galaktokomikaEidhPsugeiouController.giaSfoliata);
router.get("/freskes-zymes-fylla/fyllo-kroustas", galaktokomikaEidhPsugeiouController.fylloKroustas);
router.get("/freskes-zymes-fylla/xwriatiko-fyllo", galaktokomikaEidhPsugeiouController.xwriatikoFyllo);
router.get("/xumoi-tsai", galaktokomikaEidhPsugeiouController.xumoiTsai);
router.get("/xumoi-tsai/xymoi", galaktokomikaEidhPsugeiouController.xumoi);
router.get("/xumoi-tsai/tsai", galaktokomikaEidhPsugeiouController.tsai);
router.get("/freskoi-zwmoi", galaktokomikaEidhPsugeiouController.freskoiZwmoi);
router.get("/auga", galaktokomikaEidhPsugeiouController.auga);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/fresko-gala/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/upshlhs-pasteriwshs/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/sokolatouxo/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/futiko/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gala/evapore/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/ageladino/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/katsikisio/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/proveio/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/straggisto/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/epidorpio/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/paidiko/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/giaourti/rofhma/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/epidorpio/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/gia-krouasan/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/gia-pitsa/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/gia-sfoliata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/fyllo-kroustas/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskes-zymes-fylla/xwriatiko-fyllo/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xumoi-tsai/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xumoi-tsai/xymoi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xumoi-tsai/tsai/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/freskoi-zwmoi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/auga/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;