const express = require("express");
const router = express.Router();

const vrefikhFrontidaController = require("../../controller/products/babyCareController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", vrefikhFrontidaController.vrefikhFrontida);
router.get("/vrefiko-gala", vrefikhFrontidaController.vrefikoGala);
router.get("/vrefiko-gala/vrefiko-gala-1hs-hlikias", vrefikhFrontidaController.prwthsHlikias);
router.get("/vrefiko-gala/vrefiko-gala-2hs-hlikias", vrefikhFrontidaController.deyterhsHlikias);
router.get("/vrefiko-gala/vrefiko-gala-3hs-hlikias", vrefikhFrontidaController.trithsHlikias);
router.get("/vrefikes-trofes", vrefikhFrontidaController.vrefikesTrofes);
router.get("/vrefikes-trofes/vrefikes-kremes", vrefikhFrontidaController.vrefikesKremes);
router.get("/vrefikes-trofes/vrefika-giaoyrtia", vrefikhFrontidaController.vrefikaGiaoyrtia);
router.get("/vrefikes-trofes/vrefika-snack", vrefikhFrontidaController.vrefikaSnack);
router.get("/vrefikes-panes-mwromanthla", vrefikhFrontidaController.vrefikesPanesMwromanthla);
router.get("/vrefikes-panes-mwromanthla/vrefikes-panes", vrefikhFrontidaController.vrefikesPanes);
router.get("/vrefikes-panes-mwromanthla/mwromanthla", vrefikhFrontidaController.mwromanthla);
router.get("/aksesouar", vrefikhFrontidaController.aksesouar);
router.get("/aksesouar/piatakia-koutalakia-pirounakia", vrefikhFrontidaController.piatakiaKoytalakiaPiroynakia);
router.get("/aksesouar/vrefika-psalidakia", vrefikhFrontidaController.vrefikaPsalidakia);
router.get("/peripoihsh-swmatos", vrefikhFrontidaController.peripoihshSwmatos);
router.get("/peripoihsh-swmatos/sampouan-afroloutra", vrefikhFrontidaController.sampoyanAfroloytra);
router.get("/peripoihsh-swmatos/kremes-poudres-ladi", vrefikhFrontidaController.kremesPoydresLadi);
router.get("/vrefika-aporrypantika", vrefikhFrontidaController.vrefikaAporrypantika);
router.get("/vrefika-aporrypantika/ygra-aporrypantika", vrefikhFrontidaController.ygraAporrypantika);
router.get("/vrefika-aporrypantika/malaktika", vrefikhFrontidaController.malaktika);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefiko-gala/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefiko-gala/vrefiko-gala-1hs-hlikias/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefiko-gala/vrefiko-gala-2hs-hlikias/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefiko-gala/vrefiko-gala-3hs-hlikias/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-trofes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-trofes/vrefikes-kremes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-trofes/vrefika-giaoyrtia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-trofes/vrefika-snack/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-panes-mwromanthla/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-panes-mwromanthla/vrefikes-panes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikes-panes-mwromanthla/mwromanthla/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/peripoihsh-swmatos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/peripoihsh-swmatos/sampouan-afroloutra/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/peripoihsh-swmatos/kremes-poydres-ladi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aksesouar/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aksesouar/piatakia-koytalakia-piroynakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aksesouar/vrefika-psalidakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikh-ugieinh-dontiwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikh-ugieinh-dontiwn/vrefikes-odontovourtses/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefikh-ugieinh-dontiwn/paidika-epithemata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefika-aporrypantika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefika-aporrypantika/ygra-aporrypantika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/vrefika-aporrypantika/malaktika/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;