const express = require("express");
const router = express.Router();

const prwinoRofhmataController = require("../../controller/products/breakfastController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", prwinoRofhmataController.prwinoRofhmata);
router.get("/dhmhtriaka", prwinoRofhmataController.dhmhtriaka);
router.get("/dhmhtriaka/corn-flakes", prwinoRofhmataController.cornFlakes);
router.get("/dhmhtriaka/muesli", prwinoRofhmataController.muesli);
router.get("/dhmhtriaka/vrwmh", prwinoRofhmataController.vrwmh);
router.get("/dhmhtriaka/enhlikwn", prwinoRofhmataController.enhlikwn);
router.get("/dhmhtriaka/paidika", prwinoRofhmataController.paidika);
router.get("/dhmhtriaka/mpares-dhmhtriakwn", prwinoRofhmataController.mparesDhmhtriakwn);
router.get("/meli", prwinoRofhmataController.meli);
router.get("/meli/thumarisia", prwinoRofhmataController.thumarisia);
router.get("/meli/anthewn-kwnoforwn", prwinoRofhmataController.anthewnKwnoforwn);
router.get("/meli/alles-poikilies", prwinoRofhmataController.allesPoikilies);
router.get("/meli/basilikos-poltos", prwinoRofhmataController.basilikosPoltos);
router.get("/marmelades", prwinoRofhmataController.marmelades);
router.get("/marmelades/fraoula-kerasi", prwinoRofhmataController.fraoulaKerasi);
router.get("/marmelades/rodakino-verikoko", prwinoRofhmataController.rodakinoVerikoko);
router.get("/marmelades/vatomouro-vussino", prwinoRofhmataController.vatomouroVussino);
router.get("/marmelades/alles-geuseis", prwinoRofhmataController.allesGeuseis);
router.get("/aleimmata-karpwn", prwinoRofhmataController.aleimmataKarpwn);
router.get("/aleimmata-karpwn/pralines", prwinoRofhmataController.pralines);
router.get("/aleimmata-karpwn/taxini", prwinoRofhmataController.taxini);
router.get("/aleimmata-karpwn/fystikovoythro", prwinoRofhmataController.fystikovoythro);
router.get("/kafes-rofhmata", prwinoRofhmataController.kafesRofhmata);
router.get("/kafes-rofhmata/espresso", prwinoRofhmataController.espresso);
router.get("/kafes-rofhmata/stigmiaios", prwinoRofhmataController.stigmiaios);
router.get("/kafes-rofhmata/filtrou", prwinoRofhmataController.filtrou);
router.get("/kafes-rofhmata/ellhnikos", prwinoRofhmataController.ellhnikos);
router.get("/kafes-rofhmata/kapsoules", prwinoRofhmataController.kapsoules);
router.get("/kafes-rofhmata/upokatastata-sunodeuthka", prwinoRofhmataController.upokatastataSunodeuthka);
router.get("/kafes-rofhmata/kakao-rofhmata-sokolatas", prwinoRofhmataController.kakaoRofhmataSokolatas);
router.get("/tsai-afepsimata", prwinoRofhmataController.tsaiAfepsimata);
router.get("/tsai-afepsimata/tsai", prwinoRofhmataController.tsai);
router.get("/tsai-afepsimata/afepsimata", prwinoRofhmataController.afepsimata);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/corn-flakes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/muesli/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/vrwmh/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/enhlikwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/paidika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/dhmhtriaka/mpares-dhmhtriakwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/meli/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/meli/thumarisia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/meli/anthewn-kwnoforwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/meli/alles-poikilies/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/meli/basilikos-poltos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/marmelades/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/marmelades/fraoula-kerasi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/marmelades/rodakino-verikoko/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/marmelades/vatomouro-vussino/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/marmelades/alles-geuseis/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aleimmata-karpwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aleimmata-karpwn/pralines/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aleimmata-karpwn/taxini/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/aleimmata-karpwn/fystikovoythro/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/espresso/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/stigmiaios/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/filtrou/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/ellhnikos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/kapsoules/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/upokatastata-sunodeuthka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/kafes-rofhmata/kakao-rofhmata-sokolatas/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsai-afepsimata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsai-afepsimata/tsai/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsai-afepsimata/afepsimata/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;