const express = require("express");
const router = express.Router();

const kavaController = require("../../controller/products/drinksController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", kavaController.kava);
router.get("/krasia", kavaController.krasia);
router.get("/krasia/leuko-krasi", kavaController.leukoKrasi);
router.get("/krasia/kokkino-krasi", kavaController.kokkinoKrasi);
router.get("/krasia/roze-krasi", kavaController.rozeKrasi);
router.get("/krasia/glyka-krasia", kavaController.glykaKrasia);
router.get("/krasia/afrwdeis-oinoi", kavaController.afrwdeisOinoi);
router.get("/anapsyktika", kavaController.anapsyktika);
router.get("/anapsyktika/cola", kavaController.cola);
router.get("/anapsyktika/gkazoza", kavaController.gkazoza);
router.get("/anapsyktika/lemonada", kavaController.lemonada);
router.get("/anapsyktika/portokalada", kavaController.portokalada);
router.get("/anapsyktika/soda-tonic", kavaController.sodaTonic);
router.get("/anapsyktika/energeiaka-isotonika", kavaController.energeiakaIsotonika);
router.get("/anapsyktika/alles-geyseis", kavaController.allesGeyseis);
router.get("/xymoi-krya-rofhmata", kavaController.xymoiKryaRofhmata);
router.get("/xymoi-krya-rofhmata/xumoi-makras-diarkeias", kavaController.xumoiMakrasDiarkeias);
router.get("/xymoi-krya-rofhmata/ice-tea", kavaController.iceTea);
router.get("/xymoi-krya-rofhmata/ice-coffee", kavaController.iceCoffee);
router.get("/mpures", kavaController.mpures);
router.get("/mpures/lager", kavaController.lager);
router.get("/mpures/pils", kavaController.pils);
router.get("/mpures/weiss", kavaController.weiss);
router.get("/mpures/ale", kavaController.ale);
router.get("/mpures/radler", kavaController.radler);
router.get("/mpures/xwris-alkool", kavaController.xwrisAlkool);
router.get("/emfyalwmena-nera", kavaController.emfyalwmenaNera);
router.get("/emfyalwmena-nera/epitrapezio-metalliko-nero", kavaController.epitrapezioMetallikoNero);
router.get("/emfyalwmena-nera/anthrakouxo-nero", kavaController.anthrakouxoNero);
router.get("/pota", kavaController.pota);
router.get("/pota/ouiski", kavaController.ouiski);
router.get("/pota/vodka", kavaController.vodka);
router.get("/pota/tzin", kavaController.tzin);
router.get("/pota/roumi", kavaController.roumi);
router.get("/pota/tekila", kavaController.tekila);
router.get("/pota/mhliths", kavaController.mhliths);
router.get("/pota/tsipouro", kavaController.tsipouro);
router.get("/pota/ouzo", kavaController.ouzo);
router.get("/pota/koniak", kavaController.koniak);
router.get("/pota/liker", kavaController.liker);
router.get("/pota/aperitif", kavaController.aperitif);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/leuko-krasi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/kokkino-krasi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/roze-krasi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/glyka-krasia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/krasia/afrwdeis-oinoi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/cola/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/gkazoza/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/lemonada/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/portokalada/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/soda-tonic/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/energeiaka-isotonika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/anapsyktika/alles-geyseis/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xymoi-krya-rofhmata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xymoi-krya-rofhmata/xumoi-makras-diarkeias/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xymoi-krya-rofhmata/ice-tea/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/xymoi-krya-rofhmata/ice-coffee/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/lager/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/pils/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/weiss/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/ale/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/radler/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpures/xwris-alkool/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/emfyalwmena-nera/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/emfyalwmena-nera/epitrapezio-metalliko-nero/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/emfyalwmena-nera/anthrakouxo-nero/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/ouiski/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/vodka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/tzin/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/roumi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/tekila/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/mhliths/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/tsipouro/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/ouzo/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/koniak/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/liker/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/pota/aperitif/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;