const express = require("express");
const router = express.Router();

const opwropwleioController = require("../../controller/products/fruitStoreController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", opwropwleioController.opwropwleio);
router.get("/frouta", opwropwleioController.frouta);
router.get("/frouta/mhla", opwropwleioController.mhla);
router.get("/frouta/mpananes", opwropwleioController.mpananes);
router.get("/frouta/portokalia", opwropwleioController.portokalia);
router.get("/frouta/mantarinia", opwropwleioController.mantarinia);
router.get("/frouta/greip-frut", opwropwleioController.greipFrut);
router.get("/frouta/axladia", opwropwleioController.axladia);
router.get("/frouta/lemonia", opwropwleioController.lemonia);
router.get("/frouta/laims", opwropwleioController.laims);
router.get("/frouta/aktinidia", opwropwleioController.aktinidia);
router.get("/frouta/karpouzia", opwropwleioController.karpouzia);
router.get("/frouta/peponia", opwropwleioController.peponia);
router.get("/frouta/rodakina", opwropwleioController.rodakina);
router.get("/frouta/nektarinia", opwropwleioController.nektarinia);
router.get("/frouta/verikoka", opwropwleioController.verikoka);
router.get("/frouta/fraoules", opwropwleioController.fraoules);
router.get("/frouta/vatomoura", opwropwleioController.vatomoura);
router.get("/frouta/suka", opwropwleioController.suka);
router.get("/frouta/damaskhna", opwropwleioController.damaskhna);
router.get("/frouta/exwtika-frouta", opwropwleioController.exwtikaFrouta);
router.get("/laxanika", opwropwleioController.laxanika);
router.get("/laxanika/aggouria", opwropwleioController.aggouria);
router.get("/laxanika/tomates", opwropwleioController.tomates);
router.get("/laxanika/patates", opwropwleioController.patates);
router.get("/laxanika/kremmudia", opwropwleioController.kremmudia);
router.get("/laxanika/skorda", opwropwleioController.skorda);
router.get("/laxanika/maroulia", opwropwleioController.maroulia);
router.get("/laxanika/roka", opwropwleioController.roka);
router.get("/laxanika/etoimes-salates", opwropwleioController.etoimesSalates);
router.get("/laxanika/laxano", opwropwleioController.laxano);
router.get("/laxanika/mprokolo", opwropwleioController.mprokolo);
router.get("/laxanika/kounoupidi", opwropwleioController.kounoupidi);
router.get("/laxanika/piperies", opwropwleioController.piperies);
router.get("/laxanika/melitzanes", opwropwleioController.melitzanes);
router.get("/laxanika/kolokuthakia", opwropwleioController.kolokuthakia);
router.get("/laxanika/fasolakia", opwropwleioController.fasolakia);
router.get("/laxanika/karota", opwropwleioController.karota);
router.get("/laxanika/rapanakia", opwropwleioController.rapanakia);
router.get("/laxanika/manitaria", opwropwleioController.manitaria);
router.get("/laxanika/kalampoki", opwropwleioController.kalampoki);
router.get("/laxanika/sparaggia", opwropwleioController.sparaggia);
router.get("/laxanika/pantzaria", opwropwleioController.pantzaria);
router.get("/laxanika/murwdika", opwropwleioController.murwdika);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/mhla/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/mpananes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/portokalia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/mantarinia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/greip-frut/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/axladia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/lemonia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/laims/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/aktinidia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/karpouzia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/peponia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/rodakina/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/nektarinia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/verikoka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/fraoules/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/vatomoura/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/suka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/damaskhna/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frouta/exwtika-frouta/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/aggouria/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/tomates/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/patates/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/kremmudia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/skorda/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/maroulia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/roka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/etoimes-salates/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/laxano/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/mprokolo/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/kounoupidi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/piperies/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/melitzanes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/kolokuthakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/fasolakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/karota/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/rapanakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/manitaria/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/kalampoki/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/sparaggia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/pantzaria/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/laxanika/murwdika/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;