const express = require("express");
const router = express.Router();

const proswpikhFrontidaController = require("../../controller/products/personalCareController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", proswpikhFrontidaController.proswpikhFrontida);
router.get("/gia-andres", proswpikhFrontidaController.giaAndres);
router.get("/gia-andres/afroi-xurismatos", proswpikhFrontidaController.afroiXurismatos);
router.get("/gia-andres/xuristika-mias-xrhshs", proswpikhFrontidaController.xuristikaMiasXrhshs);
router.get("/gia-andres/aposmhtika", proswpikhFrontidaController.aposmhtika);
router.get("/gia-andres/xuristikes-mhxanes-antallaktika", proswpikhFrontidaController.xuristikesMhxanesAntallaktika);
router.get("/gia-andres/after-shave", proswpikhFrontidaController.afterShave);
router.get("/gia-gunaikes", proswpikhFrontidaController.giaGunaikes);
router.get("/gia-gunaikes/katharismos-proswpou", proswpikhFrontidaController.katharismosProswpou);
router.get("/gia-gunaikes/enudatwsh-proswpou", proswpikhFrontidaController.enudatwshProswpou);
router.get("/gia-gunaikes/xurafakia", proswpikhFrontidaController.xurafakia);
router.get("/gia-gunaikes/makigiaz", proswpikhFrontidaController.makigiaz);
router.get("/gia-gunaikes/apotrixwtika", proswpikhFrontidaController.apotrixwtika);
router.get("/gia-gunaikes/servietes-tampon", proswpikhFrontidaController.servietesTampon);
router.get("/proswpikh-ygieinh", proswpikhFrontidaController.proswpikhYgieinh);
router.get("/proswpikh-ygieinh/panes-enhlikwn", proswpikhFrontidaController.panesEnhlikwn);
router.get("/proswpikh-ygieinh/vamvakia", proswpikhFrontidaController.vamvakia);
router.get("/proswpikh-ygieinh/mpatonetes", proswpikhFrontidaController.mpatonetes);
router.get("/proswpikh-ygieinh/antishptika", proswpikhFrontidaController.antishptika);
router.get("/proionta-swmatos", proswpikhFrontidaController.proiontaSwmatos);
router.get("/proionta-swmatos/afroloutra-afrontous", proswpikhFrontidaController.afroloutraAfrontous);
router.get("/proionta-swmatos/sfouggaria", proswpikhFrontidaController.sfouggaria);
router.get("/proionta-swmatos/sapounia", proswpikhFrontidaController.sapounia);
router.get("/proionta-swmatos/kallwpismos", proswpikhFrontidaController.kallwpismos);
router.get("/frontida-malliwn", proswpikhFrontidaController.frontidaMalliwn);
router.get("/frontida-malliwn/sampouan-kremes", proswpikhFrontidaController.sampouanKremes);
router.get("/frontida-malliwn/vafes", proswpikhFrontidaController.vafes);
router.get("/frontida-malliwn/spary-gel", proswpikhFrontidaController.sparyGel);
router.get("/parafarmakeutika-eidh", proswpikhFrontidaController.parafarmakeutikaEidh);
router.get("/parafarmakeutika-eidh/epithemata-epidesmoi", proswpikhFrontidaController.epithemataEpidesmoi);
router.get("/parafarmakeutika-eidh/alkoolouxoi-losion", proswpikhFrontidaController.alkoolouxoiLosion);
router.get("/parafarmakeutika-eidh/gantia-maskes-surigges", proswpikhFrontidaController.gantiaMaskesSurigges);
router.get("/parafarmakeutika-eidh/proionta-profylaxhs", proswpikhFrontidaController.proiontaProfylaxhs);
router.get("/stomatikh-ugieinh", proswpikhFrontidaController.stomatikhUgieinh);
router.get("/stomatikh-ugieinh/odontovoyrtses", proswpikhFrontidaController.odontovoyrtses);
router.get("/stomatikh-ugieinh/odontokremes", proswpikhFrontidaController.odontokremes);
router.get("/stomatikh-ugieinh/stomatika-dialymata", proswpikhFrontidaController.stomatikaDialymata);
router.get("/stomatikh-ugieinh/stomatika-nhmata", proswpikhFrontidaController.stomatikaNhmata);
router.get("/antihliaka", proswpikhFrontidaController.antihliaka);
router.get("/antihliaka/antihliaka-swmatos", proswpikhFrontidaController.antihliakaSwmatos);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/afroi-xurismatos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/xuristika-mias-xrhshs/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/aposmhtika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/xuristikes-mhxanes-antallaktika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-andres/after-shave/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/katharismos-proswpou/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/enudatwsh-proswpou/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/xurafakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/makigiaz/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/apotrixwtika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/gia-gunaikes/servietes-tampon/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/proionta-swmatos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/proionta-swmatos/afroloutra-afrontous/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/proionta-swmatos/sfouggaria/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/proionta-swmatos/sapounia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/proionta-swmatos/kallwpismos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frontida-malliwn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frontida-malliwn/sampouan-kremes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frontida-malliwn/vafes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/frontida-malliwn/spary-gel/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/parafarmakeutika-eidh/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/parafarmakeutika-eidh/epithemata-epidesmoi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/parafarmakeutika-eidh/alkoolouxoi-losion/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/parafarmakeutika-eidh/gantia-maskes-surigges/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/parafarmakeutika-eidh/proionta-profylaxhs/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/stomatikh-ugieinh/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/stomatikh-ugieinh/odontovoyrtses/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/stomatikh-ugieinh/odontokremes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/stomatikh-ugieinh/stomatika-dialymata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/stomatikh-ugieinh/stomatika-nhmata/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/antihliaka/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/antihliaka/antihliaka-swmatos/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;