const express = require("express");
const router = express.Router();

const snacksController = require("../../controller/products/snacksController");
const fetchSingleProductController = require("../../controller/fetchSingleProductController");

router.get("/", snacksController.snacks);
router.get("/sokolates", snacksController.sokolates);
router.get("/sokolates/galaktos", snacksController.galaktos);
router.get("/sokolates/ugeias", snacksController.ugeias);
router.get("/sokolates/leukes", snacksController.leukes);
router.get("/sokolates/sokolatakia", snacksController.sokolatakia);
router.get("/sokolates/gkofretes", snacksController.gkofretes);
router.get("/mpiskota", snacksController.mpiskota);
router.get("/mpiskota/klassika", snacksController.klassika);
router.get("/mpiskota/gemista", snacksController.gemista);
router.get("/mpiskota/digestive", snacksController.digestive);
router.get("/glyka-proionta-zymhs", snacksController.glykaProiontaZymhs);
router.get("/glyka-proionta-zymhs/krouasan", snacksController.krouasan);
router.get("/glyka-proionta-zymhs/keik", snacksController.keik);
router.get("/glyka-proionta-zymhs/tsourekia", snacksController.tsourekia);
router.get("/patatakia-garidakia-pop-corn", snacksController.patatakiaGaridakiaPopCorn);
router.get("/patatakia-garidakia-pop-corn/patatakia", snacksController.patatakia);
router.get("/patatakia-garidakia-pop-corn/garidakia", snacksController.garidakia);
router.get("/patatakia-garidakia-pop-corn/nachos", snacksController.nachos);
router.get("/patatakia-garidakia-pop-corn/pop-corn", snacksController.popCorn);
router.get("/crackers", snacksController.crackers);
router.get("/ksiroi-karpoi", snacksController.ksiroiKarpoi);
router.get("/apoksuramena-frouta", snacksController.apoksuramenaFrouta);
router.get("/rizogkrofretes", snacksController.rizogkrofretes);
router.get("/tsixles-karameles", snacksController.tsixlesKarameles);
router.get("/tsixles-karameles/tsixles", snacksController.tsixles);
router.get("/tsixles-karameles/karameles", snacksController.karameles);
router.get("/tsixles-karameles/gleifitzouria", snacksController.gleifitzouria);
router.get("/tsixles-karameles/zeledakia", snacksController.zeledakia);

router.get("/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/galaktos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/ugeias/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/leukes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/sokolatakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/sokolates/gkofretes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpiskota/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpiskota/klassika/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpiskota/gemista/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/mpiskota/digestive/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/glyka-proionta-zymhs/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/glyka-proionta-zymhs/krouasan/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/glyka-proionta-zymhs/keik/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/glyka-proionta-zymhs/tsourekia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/patatakia-garidakia-pop-corn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/patatakia-garidakia-pop-corn/patatakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/patatakia-garidakia-pop-corn/garidakia/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/patatakia-garidakia-pop-corn/nachos/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/patatakia-garidakia-pop-corn/pop-corn/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/crackers/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/ksiroi-karpoi/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/apoksuramena-frouta/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/rizogkrofretes/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsixles-karameles/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsixles-karameles/tsixles/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsixles-karameles/karameles/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsixles-karameles/gleifitzouria/:id", fetchSingleProductController.fetchSingleProduct);
router.get("/tsixles-karameles/zeledakia/:id", fetchSingleProductController.fetchSingleProduct);

module.exports = router;