const express = require("express");

const router = express.Router();

const katharistikaXartikaEidhOikiakhsController = require("../../controller/viewControllers/katharistikaXartikaEidhOikiakhsController");
const authController = require("../../controller/apiControllers/authController");

router.get("/", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaXartikaEidhOikiakhs);
router.get("/kathariothta-spitiou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.kathariothtaSpitiou);
router.get("/kathariothta-spitiou/genikou-katharismou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.genikouKatharismou);
router.get("/kathariothta-spitiou/katharistika-kouzinas", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaKouzinas);
router.get("/kathariothta-spitiou/katharistika-mpaniou-toualetas", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaMpaniouToualetas);
router.get("/kathariothta-spitiou/katharistika-tzamiwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaTzamiwn);
router.get("/kathariothta-spitiou/katharistika-patwmatos", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaPatwmatos);
router.get("/kathariothta-spitiou/katharistika-epiplwn-xaliwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.katharistikaEpiplwnXaliwn);
router.get("/kathariothta-spitiou/xlwrokatharistika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xlwrokatharistika);
router.get("/kathariothta-spitiou/kata-twn-alatwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.kataTwnAlatwn);
router.get("/kathariothta-spitiou/apofraktika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.apofraktika);
router.get("/kathariothta-spitiou/sfouggaria-surmata", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.sfouggariaSurmata);
router.get("/kathariothta-spitiou/xeskonopana-sfouggaropana", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xeskonopanaSfouggaropana);
router.get("/kathariothta-spitiou/gantia-oikiakhs-xrhshs", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.gantiaOikiakhsXrhshs);
router.get("/kathariothta-spitiou/sakoules-aporrimatwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.sakoulesAporrimatwn);
router.get("/kathariothta-spitiou/skoupes-sfouggaristres-kouvades", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.skoupesSfouggaristresKouvades);
router.get("/aporrupantika-piatwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.aporrupantikaPiatwn);
router.get("/aporrupantika-piatwn/ugra-piatwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.ugraPiatwn);
router.get("/aporrupantika-piatwn/aporrupantika-plunthriou-piatwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.aporrupantikaPlunthriouPiatwn);
router.get("/aporrupantika-piatwn/alati-sumplhrwmatika-plhshs", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.alatiSumplhrwmatikaPlhshs);
router.get("/plusimo-rouxwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.plusimoRouxwn);
router.get("/plusimo-rouxwn/ugra-plunthriou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.ugraPlunthriou);
router.get("/plusimo-rouxwn/skonh-plunthriou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.skonhPlunthriou);
router.get("/plusimo-rouxwn/tampletes-plunthriou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.tampletesPlunthriou);
router.get("/plusimo-rouxwn/gia-plushmo-sto-xeri", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.giaPlushmoStoXeri);
router.get("/plusimo-rouxwn/malaktika-rouxwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.malaktikaRouxwn);
router.get("/plusimo-rouxwn/leukantika-enisxutika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.leukantikaEnisxutika);
router.get("/plusimo-rouxwn/aposklurhntiko", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.aposklurhntiko);
router.get("/eidh-siderwmatos-aplwmatos", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.eidhSiderwmatosAplwmatos);
router.get("/xarti-oikiakhs-xrhshs", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartiOikiakhsXrhshs);
router.get("/xarti-oikiakhs-xrhshs/xarti-ugeias", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartiYgeias);
router.get("/xarti-oikiakhs-xrhshs/xarti-kouzinas", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartiKouzinas);
router.get("/xarti-oikiakhs-xrhshs/xartopetsetes", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartopetsetes);
router.get("/xarti-oikiakhs-xrhshs/xartomanthla", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartomanthla);
router.get("/xarti-oikiakhs-xrhshs/ugromanthla", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.ugromanthla);
router.get("/entomoktona-entomoapothutika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.entomoktonaEntomoapothutika);
router.get("/entomoktona-entomoapothutika/entomoapothutika-xwrou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.entomoapothutikaXwrou);
router.get("/entomoktona-entomoapothutika/entomoktwna", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.entomoktwna);
router.get("/entomoktona-entomoapothutika/skoroapwthitika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.skoroapwthitika);
router.get("/fulaxh-rouxwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.fulaxhRouxwn);
router.get("/fulaxh-rouxwn/aposmhtika-rouxwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.aposmhtikaRouxwn);
router.get("/fulaxh-rouxwn/kremastres", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.kremastres);
router.get("/fulaxh-rouxwn/sakoules-fulaxhs-rouxwn", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.sakoulesFulaxhsRouxwn);
router.get("/arwmatika-keria", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.arwmatikaKeria);
router.get("/arwmatika-keria/arwmatika-xwrou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.arwmatikaXwrou);
router.get("/arwmatika-keria/keria-resw", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.keriaResw);
router.get("/grafikh-ulh-analwsima", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.grafikhYlhAnalwsima);
router.get("/grafikh-ulh-analwsima/xartika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.xartika);
router.get("/grafikh-ulh-analwsima/grafikh-ulh", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.grafikhYlh);
router.get("/dwra-paixnidia", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.dwraPaixnidia);
router.get("/eidh-autokinhtou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.eidhAutokinhtou);
router.get("/eidh-khpou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.eidhKhpou);
router.get("/BBQ-tzaki", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.BBQTzaki);
router.get("/eidh-kouzinas-mpaniou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.eidhKouzinasMpaniou);
router.get("/eidh-kouzinas-mpaniou/mageirika-skeuh-kouzinika", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.mageirikaSkeuhKouzinika);
router.get("/eidh-kouzinas-mpaniou/alouminoxarta-memvranes", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.alouminoxartaMemvranes);
router.get("/eidh-kouzinas-mpaniou/eidh-mias-xrhshs", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.eidhMiasXrhshs);
router.get("/eidh-kouzinas-mpaniou/aksesouar-mpaniou", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.aksesouarMpaniou);
router.get("/eidh-kouzinas-mpaniou/mpataries", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.mpataries);
router.get("/eidh-kouzinas-mpaniou/lampes", authController.isLoggedIn, katharistikaXartikaEidhOikiakhsController.lampes);

module.exports = router;